
###################################################################################################################################
                              ####  For Sandbox Env ####
###################################################################################################################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: voting-app-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voting-app-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  labels:
    app: voting-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      tier: frontend
  template:
    metadata:
      labels:
        app: voting-app
        tier: frontend
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: voting-app
          image: asoni007/voting-app:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: RDS_ENDPOINT
              value: voting-db.c9eeigmc69uj.us-east-1.rds.amazonaws.com
            - name: RDS_USERNAME
              value: admin
            - name: RDS_PASSWORD
              value: admin123
            - name: RDS_DB_NAME
              value: voting_db
          volumeMounts:
            - name: voting-storage
              mountPath: /data
          securityContext:
            runAsUser: 1000
      volumes:
        - name: voting-storage
          persistentVolumeClaim:
            claimName: voting-app-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-svc
  labels:
    app: voting-app
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
  selector:
    app: voting-app
    tier: frontend
